logiclearner/settings_production.py
logiclearner/settings_staging.py
logiclearner/templates/base.html
logiclearner/templates/main/index.html

Attempt to fix the lack of bundle in production as well as changed settings

Attempt to fix the lack of bundle in production as well as changed settings

---

package-lock.json
package.json
webpack.config.js

Tweak the webpack conf

---

webpack.config.js

Set public path to auto

---

cypress/integration/index.spec.js
webpack.config.js

* Make publicPath more explicit

Make publicPath more explicit

---

logiclearner/main/serializers.py
logiclearner/main/views.py
logiclearner/urls.py

Setup question list api

---

logiclearner/templates/base.html
media/scss/_typeface.scss
media/scss/_variables.scss
media/scss/main.scss

Let's begin with some font definitions!

Typeface settings

---

media/js/src/question.tsx
media/js/src/utils.ts

* Implements latex characters to question display

Implements latex characters to question display

---

media/js/src/app.tsx
media/js/src/exerciseSpace.tsx
media/js/src/question.tsx
media/js/src/questionsdashboard.tsx
media/js/src/utils.ts

* Routes the list of questions to the exercise space.
* Fixes small bug with the LaTeX conversion.

exercise space connection

---

media/js/src/exerciseSpace.tsx
media/js/src/modal.tsx
media/scss/_modal.scss
media/scss/main.scss

* Modal placeholder implementation

Modal placeholder

---

Makefile
jest.setup.ts
media/js/src/excercise.test.tsx
media/js/src/exercise.tsx
media/js/src/exerciseSpace.test.tsx
media/js/src/exerciseSpace.tsx
media/js/src/levelsDashboard.test.tsx
media/js/src/levelsdashboard.tsx
media/js/src/question.test.tsx
media/js/src/question.tsx
media/js/src/questionDashboard.test.tsx
media/js/src/questionsdashboard.tsx
package-lock.json
package.json

Add jest testing

---

media/js/src/question.tsx
media/js/src/questionsdashboard.tsx

First pass. I'm going to work on a bit more on the icons, but this PR will get us a nice view for questions dashboard.

Implementation of design for questions list in dashboard

---

media/js/src/solutionStep.tsx

* Remove handlers. Not needed.

Remove unnecessary handlers

---

logiclearner/settings_shared.py
requirements.txt

Pick up new ccnmtl settings

---

logiclearner/settings_shared.py
requirements.txt

Reverts ccnmtl/logiclearner#259

Revert "Pick up new ccnmtl settings"

---

media/js/src/exerciseSpace.tsx
media/js/src/levelsdashboard.tsx
media/js/src/question.tsx
media/js/src/questionsdashboard.tsx
media/js/src/solutionStep.test.tsx
media/js/src/solutionStep.tsx
media/js/src/utils.ts

* Interaction improvements 
* Interaction with holding and displaying correct hints. (Will probably disable the hint button for now)
* TO DO: Need to clear the input after completion of each step. 
* TO DO: Need to update immediately to complete when last step is reached. Right now it requires a refresh.

Exercise Space Interaction 2

---

requirements.txt

* Update to the latest logic tools code

Update to logictools 0.1.2

---

media/js/src/exerciseSpace.tsx
media/js/src/levelsdashboard.tsx
media/js/src/questionsdashboard.tsx
media/js/src/solutionStep.tsx
media/js/src/utils.ts

* Fixes counts and makes sure statement is saving in local storage

Fixes counts and makes sure statement is saving in local storage

---

media/js/src/exerciseSpace.tsx

* Changed the reset function to just reset the data to the original clean state instead of deleting.

Local Storage delete

---

media/js/src/exerciseSpace.tsx
media/js/src/solutionStep.tsx

* Key binding and display of past steps now in latex

Key binding and display of past steps now in latex

---

media/js/src/exerciseSpace.tsx
media/js/src/solutionStep.tsx

* Fixes completed text
* Adds checkmark to each completed step

Fixes completed text; adds checkmark to completed step

---

media/js/src/solutionStep.tsx

* Makes sure question updates are happening when deleting a step

Fixes the question status updates

---

media/js/src/solutionStep.tsx

* Add key to input to solve clearing bug
* Add a unique id to form elements

Add key to input to solve clearing bug

---

logiclearner/settings_shared.py
requirements.txt

* Trying this again, updating ccnmtl settings

ccnmtl settings upgrade

---

media/js/src/exerciseSpace.tsx

Hide hints feature

---

requirements.txt

Downgrade django-s3-sign

---

media/js/src/solutionStep.tsx

Laws in alpha order

---

media/js/src/solutionStep.tsx

* Make sure to clear errors when delete is clicked

Clear error

---

logiclearner/settings_shared.py
requirements.txt

Reverts ccnmtl/logiclearner#280

Revert "ccnmtl settings upgrade"

---

logiclearner/settings_shared.py

Change the email settings

---

media/js/src/exerciseSpace.tsx

* Scroll to the top of the exercise page

Scroll to the top of the exercise page

---

media/js/src/exerciseSpace.test.tsx

Fixes console error

---

media/js/src/exerciseSpace.tsx

* Reset scrolls to the top of the page - proofs-109

Reset scrolls to the top of the page

---

media/js/src/exerciseSpace.tsx

* Only show reset button if there is something meaningful saved

Only show reset button if there is something meaningful saved

---

media/js/src/exerciseSpace.tsx

Small typo

---

media/js/src/exerciseSpace.tsx
media/js/src/question.tsx
media/js/src/utils.ts

* keybinding to upper and lower case letters

keybinding to upper and lower case letters

---

media/js/src/exerciseSpace.tsx

* convert the solutions list to latex

convert the solutions list to latex

---

media/js/src/exerciseSpace.tsx
media/js/src/solutionStep.test.tsx
media/js/src/solutionStep.tsx
media/js/src/utils.ts

* Current delete button removes the step above. This will remove the current step.

Implementation of new delete interaction

---

requirements.txt

* Remove lti libs. Not used in this project

Remove lti libs

---

logiclearner/templates/base.html

Add privacy notice

---

logiclearner/templates/base.html
media/img/icon-reset.svg
media/js/src/question.test.tsx
media/js/src/question.tsx
media/js/src/questionsdashboard.tsx
media/js/src/utils.ts
media/scss/_card.scss
media/scss/_variables.scss

* Reset Level Functionality. Located in the Questions dashboard h2 tag

Reset Level Functionality

---

logiclearner/templates/main/tutorial.html
media/js/src/solutionStep.tsx

Remove law

---

requirements.txt

Remove the range specification

Pin django 3.2.12

---

logiclearner/main/serializers.py
media/js/src/exerciseSpace.tsx
media/js/src/utils.ts
media/scss/_question.scss

* Adds a space for the solution laws

Add laws to react space - Needs Styling

---

media/js/src/app.tsx
media/js/src/exerciseSpace.tsx
media/js/src/levelsdashboard.tsx
media/js/src/questionsdashboard.tsx

* Fixes reactga initialize error

Fixes reactga initialize error

---

media/js/src/index.tsx

* React 18 requires this change

React 18 change

---

django.mk

https://github.com/pytorch/pytorch/issues/25164

Try installing requirements with --no-cache-dir to resolve torch issue

---

media/js/src/exerciseSpace.tsx
media/js/src/solutionStep.tsx
media/js/src/tests/solutionStep.test.tsx

* Added metrics to log
* A change in how we're logging categories

Analytics events

---

media/scss/_cu-privacy-notice.scss

Reverts ccnmtl/logiclearner#529

Revert "making changes to test compressor"

---

logiclearner/settings_shared.py

This config should eventually be in ccnmtlsettings (or ctlsettings), but for now it's in the app's custom config.

Apply CAS attributes to user on login

---

requirements.txt

Reverts ccnmtl/logiclearner#699

Revert "Update django-compressor requirement from <4.0,>=3.1 to >=3.1,<5.0"

---

requirements.txt

Reverts ccnmtl/logiclearner#847

Revert "Bump urllib3 from 1.26.7 to 2.0.1"

---

requirements.txt

Reverts ccnmtl/logiclearner#891

Revert "Bump urllib3 from 1.26.7 to 2.0.3"

---

media/js/src/firstOrderLogic/firstOrderLogic.tsx
media/js/src/firstOrderLogic/statementInput.tsx

Additional changes:
* Improved the character-insert behavior for the logic symbol buttons
* Added more relationships

Allows for different regex expressionsbased on difficulty
